"""Turn a spec into two PDFs.

Templates are Jinja2 producing HTML, which WeasyPrint converts to PDF. HTML
gives real typography and table layout for almost no effort. If WeasyPrint's
system dependencies give you trouble, set RENDER_BACKEND=playwright and the
same templates go through Chrome's print engine instead.
"""

from __future__ import annotations

import io
import os
import random
from datetime import date
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates"
BACKEND = os.environ.get("RENDER_BACKEND", "weasyprint")

_ONES = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
         "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen",
         "seventeen", "eighteen", "nineteen"]
_TENS = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]


def _under_thousand(n: int) -> str:
    if n < 20:
        return _ONES[n]
    if n < 100:
        return _TENS[n // 10] + ("-" + _ONES[n % 10] if n % 10 else "")
    return _ONES[n // 100] + " hundred" + (" " + _under_thousand(n % 100) if n % 100 else "")


def number_to_words(amount: float) -> str:
    """Write a dollar amount out in words, the way a contract clause does.

    This exists for the rate_in_words defect. Those cases are not exceptions.
    They test whether extraction survives a fee stated as prose, which is
    common in contracts drafted by lawyers rather than generated by software.
    """
    whole = int(round(amount))
    if whole == 0:
        return "zero dollars"
    parts = []
    for unit, name in ((1_000_000, "million"), (1_000, "thousand")):
        if whole >= unit:
            parts.append(f"{_under_thousand(whole // unit)} {name}")
            whole %= unit
    if whole:
        parts.append(_under_thousand(whole))
    return " ".join(parts) + " dollars"


def _pretty_date(iso: str) -> str:
    return date.fromisoformat(iso).strftime("%B %-d, %Y")


def _money(value: float) -> str:
    return f"${value:,.2f}"


def _env() -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        autoescape=select_autoescape(["html"]),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["money"] = _money
    env.filters["pretty_date"] = _pretty_date
    env.filters["in_words"] = number_to_words
    return env


def render_html(template_name: str, spec: dict) -> str:
    template = _env().get_template(f"{template_name}.html.j2")
    return template.render(
        contract=spec["contract"],
        invoice=spec["invoice"],
        render=spec["render"],
        case_id=spec["case_id"],
    )


def html_to_pdf(html: str, out_path: str | Path) -> None:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if BACKEND == "weasyprint":
        from weasyprint import HTML
        HTML(string=html).write_pdf(str(out_path))
    elif BACKEND == "playwright":
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch()
            page = browser.new_page()
            page.set_content(html, wait_until="load")
            page.pdf(path=str(out_path), format="Letter",
                     margin={"top": "0.6in", "bottom": "0.6in", "left": "0.7in", "right": "0.7in"})
            browser.close()
    else:
        raise ValueError(f"unknown RENDER_BACKEND: {BACKEND}")


def scannify(pdf_path: str | Path, seed: int) -> None:
    """Rewrite a PDF in place as an image-only PDF that mimics a phone scan.

    The point is to destroy the text layer so the extraction router is
    actually forced down the vision path. Everything after that is realism:
    a slight rotation because nobody holds a phone straight, a blur because
    autofocus is imperfect, and lifted blacks because office lighting is bad.
    """
    from PIL import Image, ImageFilter
    import pypdfium2 as pdfium

    rng = random.Random(seed)
    pdf = pdfium.PdfDocument(str(pdf_path))
    pages = []
    for i in range(len(pdf)):
        img = pdf[i].render(scale=150 / 72).to_pil()
        img = img.rotate(rng.uniform(-1.5, 1.5), expand=True, fillcolor=(255, 255, 255))
        img = img.filter(ImageFilter.GaussianBlur(radius=rng.uniform(0.4, 0.9)))
        img = img.convert("L").point(lambda p: min(255, int(p * 1.04 + 10))).convert("RGB")
        pages.append(img)
    pdf.close()
    pages[0].save(str(pdf_path), save_all=True, append_images=pages[1:], resolution=150.0)


def text_layer_length(pdf_path: str | Path) -> int:
    from pypdf import PdfReader
    reader = PdfReader(str(pdf_path))
    return len("".join(p.extract_text() or "" for p in reader.pages).strip())
